### ISSUE TITLE
[FE] Add copy-to-clipboard button to URL

### ISSUE THREAD

**Issue by ioggstream** [teamdigitale/dati-semantic-frontend#136]
## Comportamento atteso

- copy/paste button near all urls in Onto, Vocab, Schemes

## Comportamento attuale

- only "open in new tab"

## Possibili soluzioni

- add copy-to-clipboard button

## Note

- it's useful for pasting urls in code editors.

**Comment by Clou-dia** [comment]
da aggiungere al backlog 2023

**Comment by Francescopalermo** [comment]
@Clou-dia 
Added a "Copy" button for each catalog item to facilitate copying the reference URL.

**Comment by Clou-dia** [comment]
The outcome is not as aspected, instead of a button use an icon 
see it-copy in https://italia.github.io/bootstrap-italia/docs/utilities/icone/ 
https://italia.github.io/bootstrap-italia/docs/utilities/icone/
This should be applied to whole semantic asset in [search](https://schema.gov.it/search), and in single semantic asset page.

as reference:
<img width="531" alt="Schermata 2024-01-29 alle 18 56 42" src="https://github.com/teamdigitale/dati-semantic-frontend/assets/98462345/fca10aa2-ac70-4c93-8746-fc6d8ccd0cdb">

<img width="500" alt="Schermata 2024-01-29 alle 18 56 34" src="https://github.com/teamdigitale/dati-semantic-frontend/assets/98462345/85a4efbe-afb3-4324-aaeb-fb7a4843c97d">

**Comment by Francescopalermo** [comment]
@Clou-dia 
fixed copy url button(now instead of that button, there is an icon) and added external link to Titolare (DETTAGLI) in Ontology, Vocabulary e Schema.

**Comment by AgostinoPurificato** [comment]
CC: @Clou-dia @mauropratesi 

@Francescopalermo can you please link the PR related to this issue?

We tested the correction on [dev environment](https://ndc-dev.apps.cloudpub.testedev.istat.it/) with a chromium-based browser and Firefox, and it looks ok.

Nevertheless, I see in the leaf page of a controlled vocabulary/ontology, only with chromium-based browser (e.g. Edge), the following visual bug:
![Screenshot 2024-02-15 151641](https://github.com/teamdigitale/dati-semantic-frontend/assets/132351416/fbf31651-1503-4d4a-ad8c-1b462bb5470a)

**Comment by Francescopalermo** [comment]
@AgostinoPurificato 
 Here there is the external link icon for Titolare:
https://github.com/teamdigitale/dati-semantic-frontend/commit/141543c169b08aedbfb4d259f080ddda73ac1098#diff-113451c214e8a94114ea9f374a974badec0800f9fb22c79dd7214503ff0503d6

Here the copy url icon fix:
https://github.com/teamdigitale/dati-semantic-frontend/commit/ee416a1bbd762b5b3e346dcb58414efa470a1a46#diff-26cd4c69d8e84dcb8867a6dac7fe6ba49da13492ee3d0fe13e184e893e39cd13
