### ISSUE TITLE
[FE] Schemi dati - Show only schema section

### ISSUE THREAD

**Issue by ioggstream** [teamdigitale/dati-semantic-frontend#345]
## I expect

- schema rendering to show only the schema model section

## Instead

- it shows operations too
- it warns when no operations are present.

## Notes

see #127

**Comment by FrankMaverick** [comment]
@AgostinoPurificato @Clou-dia @mauropratesi Yes, it is possible.

So, we hide the two highlighted parts, regardless of whether we get the data or not.

![Screenshot swagger](https://github.com/teamdigitale/dati-semantic-frontend/assets/7274755/bea90575-4d2c-41b6-b19f-cf5a66545415)

PS. I showed the swagger of a dictionary because the structure is the same.
PPS. However, the Vocabulary and Schemi are managed independently, so if we want the same change for the vocabulary too, it is better to open another dedicated issue.

**Comment by AgostinoPurificato** [comment]
@FrankMaverick maybe there is a misunderstanding.

The two highlighted parts in your screenshot are already and correctly hidden in the test environment of Catalogo Dati for data schemas (example: [link](https://ndc-test.apps.cloudpub.testedev.istat.it/semantic-assets/details?uri=https%3A%2F%2Fw3id.org%2Fitalia%2Fschemas%2Fpersona-fisica%2Flatest%2Fpersona-fisica.oas3.yaml)).

We don't want the same behavior for controlled-vocabularies, we are speaking here only about schemas.

The problem, now, is that we get the message "No operation defined in spec!", as you can see in the screenshot of my last message and also opening this [link](https://ndc-test.apps.cloudpub.testedev.istat.it/semantic-assets/details?uri=https%3A%2F%2Fw3id.org%2Fitalia%2Fschemas%2Fpersona-fisica%2Flatest%2Fpersona-fisica.oas3.yaml). Is it possible to hide **that message**?

CC @Clou-dia @mauropratesi

**Comment by FrankMaverick** [comment]
@AgostinoPurificato 
What I wanted to say is that:
Currently, the two sections are not visible because the YAML file has been modified, and automatically Swagger prints that message instead of section number 2. So, we can hide the two sections (In schema) in the frontend, regardless of whether the data (set in the YAML) arrives or not. 
Is that okay?

**Comment by AgostinoPurificato** [comment]
@FrankMaverick we are going to propose a new version of the schema's page, so we can close this issue and try to solve the related problems directly in a dedicated meeting.

Thank you.
